import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs';

// Exit-code capture hook for termag-spawned interactive shells.
//
// The broker's poll classifier wants to report 'error' when the last command
// in an unattended window failed. tmux does not expose a shell's $? directly,
// so we register a per-shell hook that writes the previous command's exit code
// into a pane-scoped tmux option (@termag_last_exit) after EVERY command. The
// agent's health poll then reads #{@termag_last_exit} per window.
//
// LIMITATION: this only works for shells termag itself launches as zsh or bash
// (see wrapWithBanner). Adopted/pre-existing sessions and other shells
// (fish/sh/ksh/dash) get NO hook — @termag_last_exit stays unset and the broker
// simply never classifies those windows as 'error'. That degradation is
// intentional and documented in banner.ts.
//
// We generate the rc files under ~/.termag/shell/ rather than touching the
// user's real ~/.zshrc or ~/.bashrc. The generated rc sources the user's real
// rc FIRST (so their config/aliases/prompt are intact) and then layers our hook
// on top, so we never clobber user config.

// The core line run after each command. $? MUST be captured as the very first
// thing in the hook so it reflects the just-finished command and not anything
// the hook itself does. set -p writes a pane-scoped option; 2>/dev/null keeps
// it silent if tmux isn't on PATH (e.g. user detached the shell from tmux).
const CAPTURE_CMD = 'tmux set -p @termag_last_exit "$?" 2>/dev/null';

// Root for generated rc files. Co-located with other termag runtime state.
function shellDir(): string {
  return path.join(os.homedir(), '.termag', 'shell');
}

// zsh reads .zshrc from $ZDOTDIR, so we point ZDOTDIR at a dir containing our
// own .zshrc. Bash has no such indirection, so we pass an explicit --rcfile.
function zdotDir(): string {
  return path.join(shellDir(), 'zsh');
}

function bashRcFile(): string {
  return path.join(shellDir(), 'bashrc');
}

// zsh: source the user's real ~/.zshrc, then append our hook to
// precmd_functions (run before each prompt, i.e. after each command).
function zshRcContents(): string {
  return [
    '# Auto-generated by termag. Do not edit; regenerated on shell launch.',
    '# Sources your real ~/.zshrc first, then layers the exit-code hook.',
    '[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"',
    '',
    '_termag_last_exit() {',
    `  ${CAPTURE_CMD}`,
    '}',
    'typeset -ga precmd_functions',
    'precmd_functions+=(_termag_last_exit)',
    ''
  ].join('\n');
}

// bash: source the user's real ~/.bashrc, then append our hook to
// PROMPT_COMMAND (run before each prompt, i.e. after each command). We prepend
// so $? is captured before any other PROMPT_COMMAND step can stomp on it.
function bashRcContents(): string {
  return [
    '# Auto-generated by termag. Do not edit; regenerated on shell launch.',
    '# Sources your real ~/.bashrc first, then layers the exit-code hook.',
    '[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"',
    '',
    `PROMPT_COMMAND='${CAPTURE_CMD}'"\${PROMPT_COMMAND:+; $PROMPT_COMMAND}"`,
    ''
  ].join('\n');
}

/**
 * Write the generated rc files to disk (idempotent). Called lazily by the
 * exec-invocation builder so launching a termag shell always uses fresh rc
 * content. Best-effort: on any fs error we return false and the caller falls
 * back to launching the shell with no hook.
 */
export function ensureShellHookFiles(): boolean {
  try {
    fs.mkdirSync(zdotDir(), { recursive: true });
    fs.writeFileSync(path.join(zdotDir(), '.zshrc'), zshRcContents(), 'utf8');
    fs.writeFileSync(bashRcFile(), bashRcContents(), 'utf8');
    return true;
  } catch {
    return false;
  }
}

/**
 * Given a resolved shell command (e.g. '/bin/zsh'), return the exec invocation
 * that launches that shell with the exit-code hook installed without clobbering
 * the user's config. For zsh/bash this points the shell at our generated rc
 * (which sources the user's real rc first); for any other shell it returns the
 * plain shell command unchanged (graceful degradation — no hook).
 */
export function shellExecInvocation(resolvedShell: string): string {
  const head = resolvedShell.trim().split(/\s+/)[0] || '';
  // Strip a leading login-shell '-' (e.g. '-zsh') before taking the basename.
  const basename = (head.split('/').filter(Boolean).pop() || '').replace(/^-/, '');

  // Only zsh/bash support the no-clobber rc indirection. Bail out (no hook)
  // for everything else, and also if we couldn't write the rc files.
  if (basename !== 'zsh' && basename !== 'bash') return resolvedShell;
  if (!ensureShellHookFiles()) return resolvedShell;

  if (basename === 'zsh') {
    // env ZDOTDIR=<dir> makes zsh read our generated .zshrc.
    return `env ZDOTDIR=${shQuote(zdotDir())} ${resolvedShell}`;
  }
  // bash: --rcfile picks our generated rc; -i keeps it interactive.
  return `${resolvedShell} --rcfile ${shQuote(bashRcFile())} -i`;
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
